//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace youngbushfireheroes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string steps { get; set; }
        public string root_link { get; set; }
        public string introduction { get; set; }
        public string isGif { get; set; }
        public string title { get; set; }
    }
}
