//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace youngbushfireheroes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Species
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string habitat { get; set; }
        public string food { get; set; }
        public string pic { get; set; }
        public string where { get; set; }
        public string endanger_status { get; set; }
        public string size { get; set; }
        public string type { get; set; }
        public string interest_fact { get; set; }
    }
}
